config/routes.rb
ViewportTester::Application.routes.draw do
  root to: "Viewports#index"
  get "/viewports", to: "Viewports#show", as: :viewport
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/viewports_controller.rb
class ViewportsController < ApplicationController
  def show
    @initial_scale = params["initial-scale"] == "" ? nil : params["initial-scale"]
    @minimum_scale = params["minimum-scale"] == "" ? nil : params["minimum-scale"]
    @maximum_scale = params["maximum-scale"] == "" ? nil : params["maximum-scale"]
    @width = params["width"] == "" ? nil : params["width"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/viewport_helper.rb
module ViewportHelper
  def viewport_content
    parts = []
    parts << "initial-scale=#{@initial_scale}" unless @initial_scale.nil?
    parts << "minimum-scale=#{@minimum_scale}" unless @minimum_scale.nil?
    parts << "maximum-scale=#{@maximum_scale}" unless @maximum_scale.nil?
    parts << "width=#{@width}" unless @width.nil?
    parts.join(', ')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ViewportTester</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="<%= viewport_content %>" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/viewports/_list.html.erb
<form action="<%= viewport_path %>" method="GET">
  <label>Width: <input name="width" value="<%= @width %>" /></label><br />
  <label>Initial Scale: <input name="initial-scale" value="<%= @initial_scale %>"  /></label><br />
  <label>Minimum Scale: <input name="minimum-scale" value="<%= @minimum_scale %>"  /></label><br />
  <label>Maximum Scale: <input name="maximum-scale" value="<%= @maximum_scale %>"  /></label><br />
  <input type="submit" />
</form>
<ul>
  <li><a href="<%= viewport_path %>">Default</a></li>
  <li><a href="<%= viewport_path "initial-scale" => 1 %>">Initial Scale: 1</a></li>
  <li><a href="<%= viewport_path "minimum-scale" => 1 %>">Minimum Scale: 1</a></li>
  <li><a href="<%= viewport_path "width" => 320 %>">Width: 320</a></li>
  <li><a href="<%= viewport_path "width" => "device-width" %>">Width: device-width</a></li>
  <li><a href="<%= viewport_path "width" => "320", "initial-scale" => 1 %>">Width: 320, Initial Scale: 1</a></li>
  <li><a href="<%= viewport_path "width" => "320", "initial-scale" => 0.5 %>">Width: 320, Initial Scale: 0.5</a></li>
</ul>

app/views/viewports/index.html.erb
<h1>Select Viewport</h1>
<%= render partial: "list" %>

app/views/viewports/show.html.erb
<p>Viewport: <%= viewport_content %></p>
<%= render partial: "list" %>
<div id="info" style="border: 1px solid #000; margin: 10px; padding: 10px">Info:<br /></div>
<div style="background-color:#ff0000; width: 320px; min-height: 100px">This div is 320px wide</div>
<div style="background-color:#00ff00; width: 640px; min-height: 100px">This div is 640px wide</div>
<script>
  var info = document.getElementById('info');
  info.innerHTML += 'window.innerWidth = ' + window.innerWidth;
  info.innerHTML += '<br />document.body.scrollWidth = ' + document.body.scrollWidth;
</script>